/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login via Google/Apple and get session JWT */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AuthLoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthLoginResponse"];
                    };
                };
                /** @description invalid_request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description invalid_id_token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description server_error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify session JWT */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthVerifyResponse"];
                    };
                };
                /** @description invalid_or_expired_token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user profile with wallet & subscription */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserProfile"];
                    };
                };
                /** @description invalid_or_expired_token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ads/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete ad watching */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AdsCompleteRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdsCompleteResponse"];
                    };
                };
                /** @description invalid_request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description invalid_ad_proof */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description server_error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/divination": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Perform divination (Streaming or JSON) */
        post: {
            parameters: {
                query?: never;
                header?: {
                    Accept?: "text/plain" | "application/json";
                    "X-Ad-Session"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DivinationRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": components["schemas"]["DivinationJsonResponse"];
                    };
                };
                /** @description missing_or_invalid_fields */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description invalid_or_expired_token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description insufficient_coins */
                402: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description rate_limited */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description server_error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/history/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List history (login only) */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                    offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HistoryListResponse"];
                    };
                };
                /** @description invalid_or_expired_token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AuthLoginRequest: {
            /** @enum {string} */
            provider: "google" | "apple";
            id_token: string;
        };
        AuthLoginResponse: {
            token: string;
            user: components["schemas"]["UserProfile"];
        };
        AuthVerifyResponse: {
            valid: boolean;
        };
        SubscriptionInfo: {
            /** @enum {string} */
            plan: "free" | "pro";
            /** Format: date-time */
            expires_at?: string | null;
            quota: number;
            remaining_gold: number;
            /** Format: date-time */
            next_refill_at?: string | null;
        };
        WalletInfo: {
            silver: number;
        };
        UserProfile: {
            id: string;
            email?: string | null;
            display_name?: string | null;
            subscription: components["schemas"]["SubscriptionInfo"];
            wallet: components["schemas"]["WalletInfo"];
            history_limit: number;
        };
        AdsCompleteRequest: {
            /** @enum {string} */
            provider: "admob" | "unknown";
            ad_proof: string;
        };
        AdsCompleteResponse: {
            /** @enum {string} */
            reward_type: "silver";
            silver_granted: number;
            new_silver_balance: number;
        } | {
            /** @enum {string} */
            reward_type: "unlock";
            ad_session_token: string;
            expires_in: number;
        };
        DivinationRequest: {
            question: string;
            throws: (6 | 7 | 8 | 9)[];
            user_name?: string | null;
            client_context?: {
                /** @enum {string} */
                app?: "web" | "ios" | "android";
                version?: string | null;
            } | null;
        };
        DivinationJsonResponse: {
            reading_id?: number | null;
            hexagram_code: string;
            changing_lines: number[];
            content: string;
            saved_to_history: boolean;
        };
        HistoryListItem: {
            reading_id: number;
            question: string;
            /** Format: date-time */
            created_at: string;
            is_pinned: boolean;
        };
        HistoryListResponse: {
            items: components["schemas"]["HistoryListItem"][];
            total: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
